### ISSUE TITLE
HaRpcProxyFactoryBean的keepAlive=true的情况下是短连接调用吗？

### ISSUE THREAD

**Issue by wangzheng0822** [jhunters/Jprotobuf-rpc-socket#42]

**Comment by jhunters** [comment]
长短连接的控制只能通过 RpcClientOptions的 shortConnection来设置

**Comment by wangzheng0822** [comment]
Spring下怎么配置呢？

**Comment by jhunters** [comment]
<bean id="echoServiceProxy" class="com.baidu.jprotobuf.pbrpc.spring.RpcProxyFactoryBean">
		<property name="serviceInterface" value="com.baidu.jprotobuf.pbrpc.EchoService"></property>
		<property name="port" value="1031"></property>
		<property name="shortConnection" value="false"></property>
	</bean>
